### ISSUE TITLE
Mail Link

### ISSUE THREAD

**Issue by MohamedAliyarAR** [ruppysuppy/ruppysuppy#3]
I think the mail link  provided might be wrong in the link section 
~~~
 [![gmail](https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=Gmail&logoColor=white)](mailto:https://github.com/ruppysuppy) 
~~~

**Comment by ruppysuppy** [comment]
Thankyou @MohamedAliyarAR got it fixed https://github.com/ruppysuppy/ruppysuppy/commit/1a0e76d702c807706a37bf07563f5e57413dd5d2
